code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/simple_animal/friendly/cat.dm
code/modules/mob/living/simple_animal/parrot.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/vore/resize.dm
code/modules/vore/vore.dm

Things changed:
- Renamed all the `endo` verbs to `digest_(stomach/cock/boob/whatever)`
- Should be hopefully less confusing.
- Cleans up the cat and parrot files a bit.
- did anyone notice that parrots cannot actually pick anyone up
- Adds a few more constants, used for averaging. These don't ever need to be changed, they just find the average between all of the sizes, for better admin compatibility.

Clean up a few things.

---

code/modules/vore/voretype/unbirth.dm

It makes more sense and is filename consistent and makes it compile.

Rename voretype 'womb' to 'unbirth'

---

code/modules/admin/admin.dm
code/modules/admin/topic.dm
code/modules/events/event_manager.dm

For Issue #111
* Reorganized the secrets panel to be a bit nicer to look at, now it has tabs for different categories instead of being a big long list.
* Also changed it to use the nano theme just to be nice.
* Added the ability to immediately start an event with a button press to the event manager panel.   Convenient!

Secrets and Events

---

maps/exodus-5.dmm

Just added a camera to the new mining base breakroom.

Add camera on exodus-5

---

code/game/jobs/job/captain.dm

Remove spurrious return statement to fix Issue #187

Loyalty Implant For HOP

---

code/modules/projectiles/guns/energy/nuclear.dm

Per convo with Ace, changed cost of firing egun stun setting.

E-Gun Rebalance

---

code/game/jobs/job/civilian_chaplain.dm

I looked at one of the issues in this github and decided to set on something simple to help out people, the ALT TITLES are the only variable I changed and I added quite a few, understand this is only the file for the chaplain. I will throw the changes down bellow since I haven't used github in a while and I'm unsure if it records any of that.
alt_titles = list("Counselor","Therapist","Preist","Cleric","Divine","Monk","Preistess","Pope")
As above, I added a few for example and might decide to add more if we really need it. I want to look at the other jobs and do the same if this commit gets accepted. - I've also tested this and compiled it.

Updated alt_titles Chaplain

---

code/game/dna/dna_modifier.dm

* Changed to let users enter DNA scanners simply by walking into them.
* Also added code comments to the DNA modifier computer to help
understand its complex mysteries
* Fixed two potential runtime-error cases in the DNA modifier computer's
code that could occur if occupant was somehow removed but UI window was
still open.

Enter DNA Scanner by Bumping

---

code/modules/mob/living/carbon/human/update_icons.dm
code/modules/mob/new_player/sprite_accessories.dm

When on marked tail choices that don't have tails (such as bat wings),
show the species tail if they have one. DIY tajara succubi!

Show species tails when appropriate

---

code/modules/customitems/item_defines.dm

Makes all autoinjectors not microcillin

---

code/modules/mob/new_player/preferences_setup.dm

Character Setup preview images now show taur-body and custom ears/tails.

Character Setup Preview

---

code/game/jobs/job/medical.dm
html/changelogs/arokha-PR-229.yml

Fixes #140 by adding CMO maint access

Fix for #140

---

code/modules/mob/holder.dm
code/modules/vore/vore.dm
code/modules/vore/voretype/voretype.dm
html/changelogs/arokha-PR-232.yml

1) Held micros now look like the person rather than the black silouette
2) You can examine micros to get their normal description as you would a
person
3) Micros now receive vore messages when being eaten (consequently also
fixed it so that prey in people get vore messages too)

Mini-micro update!

---

code/__HELPERS/global_lists.dm
code/game/dna/dna2.dm
code/game/dna/dna2_helpers.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/carbon/monkey/monkey.dm

Adds what the title says, and it's kept via genetics.

Size on character select screen

---

code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm

If user canceled out of the dialog box selecting playerscale or taur
body, an out of range value would be returned.  Altered to not change
the value if canceled out.
Also changed display of playerscale to be a percentage. Looks nicer.

Fix Char Setup Cancel Selection

---

code/modules/vore/vore.dm

It's in the vore tab. Turns on digestion for 20 minutes, then back off.
Can also turn it off early. Has a warning box for both directions.

Mob digestion toggle verb

---

code/game/jobs/job/security.dm

Added HUD Glasses to officer spawn

---

VOREStation.dme
code/game/objects/effects/grav_pull.dm
code/modules/reagents/Chemistry-Reagents.dm
code/modules/reagents/Chemistry-Recipes.dm

* Added "Normalcillin" a drug that returns you to normal size!
* Refactored the code for these reagents, removed dead code and cleaned
up the if statements to make it more datum driven and remove
duplication.
* Added chemistry recipes for crafting the micro/macro/normal cillin
* Added "sizeoxadone" as an intermediate precursor to them for game
balance.
* Added a fun effect upon mixing micro and macrocillin together.

Make Micro/Macro Reagents Craftable

---

code/modules/reagents/reagent_containers/food/drinks.dm

More reasonably matches existing container sizes

Shaker transfer options

---

maps/exodus-1.dmm

Fix camera name in genetics

---

code/modules/mob/new_player/sprite_accessories.dm

Add black cat ears

---

code/game/jobs/whitelist.dm

Makes the skeleton whitelist only HOTFIX

---

code/global.dm

Changes an non-existant chemical to an actual chemical in the code.

Fixes a non-existant chemical stopping hearts

---

code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/vore/belly/belly_tail.dm
code/modules/vore/vore.dm
code/modules/vore/voretype/tail.dm
code/modules/vore/voretype/voretype.dm

I was told that tail vore was already in development/waiting to be coded/added, so I went ahead and made it.
Functions like any other type of vore.
Photos to show all the functions in action:
http://puu.sh/n4kr5/740c87cb43.png (Eating)
http://puu.sh/n4kAO/f2fc0c7bcf.png (Holding)
http://puu.sh/n4kEM/1196dc9d65.png (Digestion)
http://puu.sh/n4kHo/668b6c3b7f.png (Release)
http://puu.sh/n4kJk/7a217e9b43.png (Flavor text)
Tested and it's fully functioning and ready for merge.
Also incorporates PR #371 into it, making it so there isn't any compiling errors.

Adds tail vore.

---

code/game/machinery/status_display_ai.dm
code/modules/vore/voretype/tail.dm

Exactly what it says on the tin.
Also fixes a spelling error in tail.dm
https://i.gyazo.com/58a9c6b6d1c74a8e43526239f428a175.mp4 (Gif of the emotion)

Adds a "fish tank" AI emotion to selectiable emotions

---

code/modules/mob/new_player/sprite_accessories.dm

Allows any race to have another races tail (Ex: Tajaran with Sergal tail.) ALSO incorperates #392 
Adresses issue #385

Allows species specific tails to be chosen.

---

code/modules/vore/belly/belly_womb.dm

Completely fixes womb transformations.  
Automatically updates the taur half, so the hotfix button isn't needed anymore.
Also makes it so the "change species" actually changes the prey's species and taur.

Completely fixes womb TF. (No taur fix button needed.)

---

code/modules/hydroponics/seed_datums.dm

Stops walking mushrooms from self harvesting to fix issue #414

Stops mushrooms from self harvesting (Hotfix)

---

code/modules/mob/new_player/sprite_accessories.dm

Forgot to add this in with the original PR.
Example: http://puu.sh/nruld/3344b590cf.png

Adds hair colored species-specific tails. (Hotfix?)

---

code/game/objects/items/weapons/circuitboards/machinery/research.dm
code/modules/research/designs.dm

Exactly what it says on the tin.
Allows R&D to create suspension field generators for xenoarcheoligsts.
Fixes #426

Allows suspension field generators to be fabricated in R&D

---

code/modules/mob/language.dm
code/modules/vore/belly/belly_womb.dm
code/modules/vore/spiderTaurPowers.dm

Fixes Nevreans auto talking over sci comms, and allows the nervian language to be used correctly.

Some bugfixes and edits

---

code/game/machinery/vending.dm
code/modules/client/preferences_gear.dm
code/modules/mob/language.dm
code/stylesheet.dm

Added demonish language, fixed birdsong language color. Added swimsuits to custom loadout and the univend (purple is best :3).
The birdsong language was supposed to have a pinkish color when you type, but you have to define the colors in the css stylesheet, so I did. I think the birdsong color is too bright, but it's not my place to change it.
The demon language uses .8 , no other language was using it so shouldn't be an issue. Has a darkish redish color to it. It is selectable as a secondary for all languages, and is meant for succubus and other demon chars :3.

Demon language, birdsong language color fix. Also swimsuits

---

code/game/dna/dna2.dm
code/modules/vore/spiderTaurPowers.dm

Completely eliminates spam of spiderwebs by commenting it out.
Leaves in the spider binding suit thingy to allow spiders to still rp binding people up, but removes them being able to place down all the damn tiles.
Addresses #450

Removes spider webs to prevent mass spam.

---

code/stylesheet.dm

As title says. 
Addresses #452

Changes birdsong color to one that is friendly on the eyes.

---

code/modules/vore/voretype/tail.dm

Exactly what the title says. People were complaining about its length/how disgusting it sounds, so I went ahead and changed it.

Replaces the tail vore sound with one much more fitting and shorter.

---

code/modules/organs/organ_internal.dm
code/modules/reagents/Chemistry-Reagents.dm

https://github.com/SpadesNeil/VOREstation/issues/478
Howdy,
Alcohol metabolism now depends on your size. From largest to smallest you can tolerate 
(4.5, 2.5, 1, 0.75, 0.5)
Times the drink of a normal person.
I also adjusted the rate at which alcohol can cause tox damage. This should help not-swamp-medbay with the increase in drinking from the larger sizes. Also it's probably more realistic.

Alcohol Metabolism Changes (Kills liver slower. Size affects drunkenness)

---

code/game/gamemodes/changeling/changeling_powers.dm

Exactly what it says on the title
Does 10 damage, and 60 agony damage. (Enough that you get a cut that heals quickly, and it hurts like all hell. Turns your health doll red, while not actually doing the damage.)

Changelings absorbing people doesn't kill

---

code/modules/research/designs.dm

Fixes Issue #500 by adding flaura disks to R&D constructable items

---

code/game/objects/items/weapons/dogborgstuff.dm
code/modules/research/designs.dm

Exactly what the title says. Really urgent hotfix.
Prevents borgs from eating people when they move away
Prevents borgs from eating two people at once and permanently trapping people in their stomach.
Note: I have no idea why the additions in design.dm is showing up. That was added in a completely seperate PR. I'm assuming it's because I merged the newest master branch while adding this? Dunno.

Fixes borgs stomachs from eating 2 people at once and eating from afar. HOTFIX

---

code/modules/client/preferences_factions.dm

- Alphabetized
- Organized
- Updated
- Corrected

Fluff Factions updated

---

code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/carbon/human/emote.dm
code/modules/mob/living/carbon/human/human.dm

Reverts SpadesNeil/VOREstation#525

Revert "Vore Preferences in Flavortext Addition"

---

code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/carbon/human/emote.dm
code/modules/mob/living/carbon/human/human.dm

Adds in preferences. #524 
Unknown forgot to add a + to the flavortext addition. It was
flavor_text = flavor_texts["preferences"]
instead of
flavor_text += flavor_texts["preferences"]
This fixes that. Fully bugtested. 
Proof that this works:
http://puu.sh/o9KTr/9f6212de8a.png

Adds in preferences. (FIXED)

---

code/game/machinery/rechargestation.dm

Let's use like, proper case and stuff.
Also made 'exit' only show up when in a charger.

Recharge station wording

---

code/game/machinery/portable_turret.dm

Removes unused(?) callback from porta-turrets

---

code/game/machinery/telecomms/logbrowser.dm
code/game/machinery/telecomms/telemonitor.dm

Fixes missing telecom terminal frames.
Fixes #552

Fix for #552

---

code/modules/admin/topic.dm

More liberal player note adding when banning, jobbanning, unbanning,
editing bans, etc.
Fixes #476

Fix for #476

---

code/game/mecha/mecha.dm
code/modules/clothing/spacesuits/rig/rig_attackby.dm

Lets you use wallets on exosuits (and rigsuits because I was not 100% sure
what the person reporting it was referring to, and both needed fixing).
Fixes #494

Fix for #494

---

code/__HELPERS/global_lists.dm
code/game/jobs/whitelist.dm
code/modules/mob/new_player/new_player.dm

Now it ONLY uses the "IS_WHITELISTED" species flag, not a magic text list.

Fixes species whitelist to be consistent

---

code/modules/client/preferences.dm

Fixes #593 by extending the borgs pref limit.

Fixes #593 Extends borgs text limit.

---

code/game/machinery/alarm.dm
code/game/objects/items/devices/megaphone.dm
code/modules/mob/living/silicon/robot/dogborg/dog_sleeper.dm
code/modules/mob/living/silicon/robot/inventory.dm
code/modules/mob/living/silicon/robot/life.dm
code/modules/mob/living/silicon/robot/robot.dm
code/modules/power/apc.dm
code/setup.dm

Air alarms don't trigger if on Z 7+, megaphone works anywhere (even through walls, it's fuggin loud okay), 200 age limit, reduced updateicon() calls for borgs (was laggy), fixed typing icon for borgs, fixed dogborg 'eye lights' sprite, added resting/sleeping and dead sprite for dogborgs.
Commits list/reference the fixed issues. Should auto-close them.

Several Bugfixes

---

code/modules/awaymissions/gateway.dm

Gateway sound

---

VOREStation.dme
code/modules/mob/living/silicon/robot/life.dm
code/modules/mob/living/silicon/robot/robot.dm
code/modules/mob/living/silicon/robot/whisper.dm

Adds whispering to borgs. Was annoying to RP without that. I'll have to add subtle emotes too but that's a lot more complicated. Also made it turn off your light when resting. Also think I caught a bug about the dogborg resting anim.

Borg Whispering

---

code/modules/mining/abandonedcrates.dm

Made a more humane code, example can be used for other such problems and
the puzzle maps.
fixes #624
Thank you for your help.

Fixes Abandoned Crates bug

---

code/game/machinery/telecomms/traffic_control.dm
code/modules/research/designs.dm

Also fixed screen for telecoms traffic comp.
Also fixed printing of circuit board while we are at it.

Followup to #622 - Also fixed screen for telecoms traffic comp.

---

code/modules/vore/_constants.dm
code/modules/vore/belly/belly.dm
code/modules/vore/belly/belly_modes.dm
code/modules/vore/vore_panel.dm

Same as the last TF setup, but made to work with the new-vore system. No differences other than that.

Adds TF to the new vore system.

---

code/modules/vore/vore_panel.dm

I accidentally made a branch. Whoops!

Fixes a bug saying "I think you're human"

---

code/game/machinery/teleporter.dm
code/game/objects/items/weapons/teleportation.dm

- Changed test-firing to last 10 minutes.
- Hand tele accuracy is based on base teleporter accuracy.
- Hand tele target select shows "Accurate" if hub is accurate.
Hopefully Resolves #630

Tweak for #630

---

code/game/objects/items/weapons/teleportation.dm

No idea why these are happening but this cleans it up. The silly way they were doing it was dumb anyway.

Fix Runtimes

---

code/game/objects/items/weapons/defibvest.dm

Lowered the chances of success. Fixed battery insert proc to not leave the battery hanging.

Tweaks to AED Vest

---

code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/reagents/Chemistry-Holder.dm
code/modules/vore/belly/belly.dm

If you digest someone you get 50% of their reagents. If you ABSORB
someone, YOU get 100% of their reagents, and THEY start using YOUR
reagents as their own.
When released, they take a proportionate amount of reagents (depends on
how many other absorbed prey). Like with just 1 absorbed person, the pred
keeps half and prey gets half. With 2, they get a third, etc.
Also tweaks human examine text so that the weight messages aren't ALL red.

Prey Reagents -> Preds

---

code/game/machinery/alarm.dm

You know, I changed this like 2 updates ago. I'm surprised the station still exists.
!src.z >= 7
src.z < 7
Fixes #692

Fix for #692

---

code/modules/client/preferences_savefile.dm

Actually not true. It DOES save. It just doesn't load. But really what's the difference.

Digestable Setting Not Saving

---

code/modules/vore/vore_panel.dm

Fixes previous fix
