SpadesNeil/VOREstation

code/modules/mob/holder.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/carbon_defines.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/mob_grab.dm, code/modules/vore/vore.dm
This PR cleans up some of the old code ported by PR #2.
Systems refactored:
- Most of vore.dm
- Most notable changes are to the release verb, which should function properly now when a mob releases another mob inside a mob.
- Carbon relaymove
- 2 second delay between messages _actually works now_
- vomit() and the release verb should properly function now, adding people to the right lists if they are released inside another mob.
- Inside panel 
Systems cleaned and prettied up:
- Holder afterattack code, cleaned up with spaces and table-of-contents-esq comments.
- Also, a note, preattack isn't a thing. afterattack is the correct thing to override.
- Grab-eating, cleaned with spaces and table-of-contents-esq comments.
- handle_x() Life() procs separated and spaced out a bit, …
=> Clean up Vore features port

code/game/machinery/atmoalter/meter.dm, code/game/machinery/atmoalter/scrubber.dm, code/game/machinery/machinery.dm
:white_check_mark: **New Features**
* Portable Scrubber Dialog now allows configuring which gases the unit scrubs!
* To reduce greifing this function is locked, requires atmos ID to
unlock.
:wrench:  **Fixes**
* System Wide:
* Fixed "usr" vs "user" typos in /obj/machinery
* To  Portable Scrubber:
* Fixed  names to not be proper nouns (so 'the' is not omitted)
* Changed the panel to use the NT UI theme
* Enhanced the user of super-type calls to take advantage of shared code
in /obj/machinery - results in less code duplication and better support
for when you can/can't use machines.
* To Gas Meters
* Gas meters can once again be read just by clicking on them. (#53)
=> Atmos Machinery Enhancement

nano/js/nano_base_helpers.js
:wrench: Fixes
* Fixed PDA Buttons to actually look like a button with blue background.  ( #50 )
* In the javascript function which handles button links in nanoui
templates, if the elementClass parameter (which allows specifying a
custom css class for this link) was passed then the link HTML was being
generated *without* the "link" class.    The link class is what makes it
look properly like a button.
=> Issue 50: Fix PDA Button Backgrounds

code/game/objects/items/stacks/sheets/glass.dm, code/modules/mining/alloys.dm, code/modules/mining/machine_stacking.dm, code/modules/mining/ore_datum.dm
Currently there is no way to make phoron glass.
Regular glass comes from sand, so I figure mixing 2x sand + 1x phoron ore should give 1x
phoron glass.   
* Added that formula to alloy datums so it can be made at the mining base.
* Also made the stacking machine recognize it can stack phoron glass.
* Fixed a bug where creation of reinforced phoron glass would also create regular reinforced glass.
=> Phoron Glass

code/datums/mind.dm, code/game/jobs/job/captain.dm, code/game/jobs/job/civilian.dm, code/game/jobs/job/security.dm, code/modules/admin/verbs/striketeam.dm, code/modules/mob/living/carbon/human/human.dm, config/example/game_options.txt
This is a fix to issue #101 
* Attempting to enable loyalty implants in config caused runtime errors
on join; this is because the job definitions were incorrectly calling
the implant_loyalty() proc.
* The implant_loyalty proc was stupid.  It was defined on
mob/living/carbon/human, but didn't act on its 'src', you had to pass it
another carbon/human as a parameter.  This makes no sense whatsoever.  I
just fixed it to be sane.
* is_loyalty_implanted() proc had the same issue.
=> Fixed Loyalty Implants

code/game/turfs/simulated/walls_mineral.dm, code/modules/supermatter/supermatter.dm
* Baycode turned off radiation collectors working with supermatter.
Restored it!
* Hey, Uranium walls irradiate people, lets make them work with
radiation collectors too!  Also they should radiate when hit with
emitters, for superfun.
=> Supermatter Powers Radiation Collectors

code/modules/mining/mine_turfs.dm, code/modules/random_map/random_map.dm
Minerals on the asteroid consist of the underground resources and the actual turf itself.  The distribution of surface turf minerals resulted in very low amounts.
Part of this is because it distributes it randomly throughout the designated asteroid area, without actually checking if the tile it plans to put minerals on is actually designated in the map as randomizable (masked).   When it comes time to actually place the minerals, non-masked tiles are skipped, so you end up with less minerals than planned.  This can be solved by simply checking.
The second issue is that the map generator decides to place a bunch of mineral turfs, but the turf itself then randomly picks what type.   This does not happen until its instantiated; too late to efficiently try and reroll. Instead we have …
=> Asteroid Mineral Distribution Overhaul

code/game/machinery/vending.dm, code/modules/client/preferences_gear.dm
Added e-cigs to vendors (pricey!)
Added e-cigs to character setup fluff item list
These are not custom, they were in Bay already, with no way to obtain them. Now they cost 250% as much as a pack of smokes, but don't hurt your lungs. Hooray. A couple of players requested this, and I wanted to practice coding so.
=> The "Stop Smoking" Commit

code/modules/admin/topic.dm, code/modules/reagents/reagent_containers/spray.dm
* Fixed pepperspray to not make noise nor alert admins if it does not
actually spray due to safety being on. (Issue #130) 
* Change CentCom fax replies to use BBCode in order to be consistent with
other faxes. (Issue #114 )
=> Pepperspray noise and CC Fax Reply

code/__HELPERS/type2type.dm, code/game/dna/dna2.dm
* The proc num2hex was incorrectly padding on extra zeros.  Instead of
padding to a given length if the hex was too short, it would pad more
the longer the hex was!  Result of transposed variables in subtraction.
* At the same time, given that num2hex already pads to 3 digits, there
is no reason whatsoever to call add_zero2() in dna processing.
* Fixes Issue #131
=> Fixed DNA Editor

code/modules/mob/emote.dm
When a micro is held, emotes are heard twice by the held micro and any
prey inside the holder of the micro.
Fixed by not passing custom emotes, since the new search-for-viewers
code seems to pick up people inside anyway.
Addresses Issue #133
=> Emotes Heard Twice When Micros Held

code/game/objects/items/weapons/storage/storage.dm
Fixes #56 - Issue was that the screen_loc was never being cleared on the
items when they are put into the part replacer, so they continue to be
rendered where they were.
=> Fix Putting Items In Part Replacer

code/game/jobs/job/security.dm
Fixed #175 - Increased total job cap for security to 5 now that we do
not have blue shield.
I left spawn cap to 3 to avoid unintentional flooding on server start;
this can always be changed if inconvenient.
=> Increase Job Cap on Security

code/game/verbs/ooc.dm, code/modules/admin/admin_verbs.dm, code/modules/client/preferences.dm, code/modules/client/preferences_toggles.dm, code/modules/mob/typing_indicator.dm, code/setup.dm
* Finished Issue #170 
* The existing "toggles" variable for preference flags was full (BYOND
supports only up to 16 bit bitstrings) Therefore a new one was created; this one is specifically for "runtime" preferences that reset every game start.  (This is both ideal for our RLOOC squelching, which we want to be opt-in, and also convenient because it does not affect the savefile format)
* Add a new bit that toggles hearing (R)LOOC
* Add a new admin verb to toggle the preference bit.
* Changed LOOC verb to not transmit to admins with the CHAT_RLOOC runtime toggle set to false.
Also: :wrench: Fixed: The Typing Indicator Toggle verb works, but the message it prints is the
opposite of what it actually did.
=> Made Remote LOOC Toggleable

code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/human/human.dm
Added a 'Custom Species' that you can set on character setup, which
overrides the examine text species. So if you're a demi you can set this
and your examine text will not omit species (it did this for humans). If
you're an anthro and using sergal and tajara you can put 'red fox' or
whatever and it will say that instead.
preferences.dm: Added custom_species and entry on character setup screen,
and to add this to the character.custom_species variable
preferences_safefile.dm: Updated savefile to save custom_preferences
carbon/human/examine.dm: Added override for species examine text if
custom_species is defined
carbon/human/human.dm: Added custom_species variable (undefined)
=> Add 'Custom Species' Setting for Examine

code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/vore/resize.dm
+ Re-add micro foot interactions, addresses Issue #83
+ Make micros centre on tiles again, addresses Issue #82
Also makes the foot code semi-compatible with xenomorphs. Odd behaviour can be exhibited while they're the macro, untested as micro, but unlikely to ever come up outside of admin-run events.
To elaborate on "odd xeno behaviour" - help intent seems fine, harm intent seems fine, grab intent defaults to disarm because xenomorphs don't have a foot slot to equip micros to, but disarm intent just does nothing, pushes them instead.
--- UPDATED 21/10/2015 AT 00:55 BECAUSE BRITISH FUCK YOU GUYS ---
+ Updated resize.dm and update_icons.dm to use the constants instead of integer values
=> Night micros

code/game/machinery/machinery.dm
* Telco machines did not instantiate component_parts in constructor.  To
prevent stuff that assumes it is a list from failing, we init to empty
list so all machines behave consistently
=> Fix Issue #161 (Telco Machine Construction)

code/game/jobs/job/civilian.dm
I wondered why they had removed some of the extra titles from the new version of baycode. Of course, these things only usually add to the game if we're talking about using them in a RP server. I decided to add a few back, but I'm still lacking on ideas for other job titles.
=> Civilian alt_titles added

code/__HELPERS/global_lists.dm, code/game/dna/dna2.dm, code/game/dna/dna2_helpers.dm, code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/mob/new_player/sprite_accessories.dm
* Enhance how taur-body sprites are implemented by replacing hard coded lists and switch statements with a new datum which defines details about taurs.
* Changed the load/save and icon drawing to reference the list of singleton datum instances instead.
* Now Taur-type is Block 19 of UI in DNA.
Advantages:
* New taur types can be added simply by appending an additional datum. No editing elsewhere in code required, it is all automatic.
* Taurs show up on the character setup screen by name instead of just by number.
* **Taurs stay tauric when cloned!** 
* No more hard coded numeric indexes, its all data-driven code.
=> Taur Enhancement and Cloning

VOREStation.dme, code/game/machinery/kitchen/gibber.dm, code/game/machinery/kitchen/microwave.dm, code/game/machinery/kitchen/smartfridge.dm, code/game/objects/items/weapons/circuitboards/machinery/kitchen.dm, code/modules/research/designs.dm
Make kitchen machines (Microwave, Gibber, and Smartfridge) constructable
* Add a circuit board item for each so its constructable
* Add circuit boards to R&D datums so the boards are printable
* Add components to New() for each
* Add handlers for screwdriver/crowbar to each so they are
de-constructable.
* Add part replacer handler to each so parts are replacable.
=> Constructable Kitchen Machines

code/modules/mob/living/carbon/human/update_icons.dm
Moved tail layer down. Prevents it from rendering under back and suit
slot.
There are downsides to any layer placement. Nothing will make this perfect
unfortunately. Some placements decide whether something looks good from
the front or back, but not good from both.
And not every suit slot item is really a back item. Stun batons generally
aren't. But MOST are weapons worn on the back, and we can only make it
look good for MOST things, sadly.
=> Re-arranged update_icons layers

code/game/objects/items/devices/multitool.dm, code/game/objects/items/weapons/circuitboards/computer/air_management.dm
* Circuit board needs to retain not only the frequency but also list of
sensor IDs in order to properly rebuild the same computer.
* You cannot just set the frequency var, you must call set_frequency()
for it to take effect
* While we are here, lets make examining the board show the frequency
configured.
* While we are here, lets make it possible to link up air sensors and
atmos computers!
=> Atmos Sensor Computers (Fix #234)

code/modules/vore/belly/belly.dm
On vore bellies, we add an additional proc to allow cleanly releasing
individual atmos instead of all contents of the belly.
=> Make specific atoms releasable

VOREStation.dme, code/modules/mob/living/living.dm, code/modules/mob/living/simple_animal/friendly/cat.dm, code/modules/mob/living/simple_animal/friendly/fox.dm, code/modules/mob/living/simple_animal/parrot.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/vore/belly/belly_simple.dm, code/modules/vore/belly/belly_stomach.dm, code/modules/vore/vore.dm
Lots of changes.
-Gave simple_animal mobs their own 'simple' belly type that sends messages
to prey, in lieu of having an actual RP partner.
-Defined 48 or so emotes to be used for this purpose and added comment
blocks for people to add the rest that I wasn't creative enough to do.
-Rebalanced how fox and cat hunt. They were a bit 'homing missile' in the
past, they are a bit easier now.
-OOC escaping from a mob adds you to be excluded from being re-eaten for 5
seconds.
-Mobs now respect the no-digesting flag, and use the same vore bellies as
everyone else.
-Added custom emotes for Renault and Runtime to emote into their bellies
when they have prey. Go get ate!
-Refactored OOC escape code to clean up belly listings inside the pred and
just use the belly functions to get out.
-Split OOC …
=> simple_animal changes

code/datums/supplypacks.dm
To get a name without instantiating, need to follow a specific syntax.
This is it.
=> Fixes #179 - Cargo manifests don't show contents

code/game/machinery/requests_console.dm
Make the messages on a request console printable so you can keep a copy
with you when attempting to fufill the request.
=> Request Consoles Printable

code/game/objects/items/weapons/circuitboards/machinery/research.dm, code/modules/mob/holder.dm, code/modules/reagents/reagent_containers/food/snacks.dm, code/modules/research/designs.dm, code/modules/vore/belly/belly_stomach.dm
Change for #272 
Updated micro holders to have a GetAccess() that the normal access-checking routines can call, that gets and returns the access from the micro inside the holder.
Fix for #252 
Feeding self had nutriment limit raised to 6000 but not feeding others. Corrected this.
Addition for #42 
Added two circuitboards to the printer for the xenoflora machines.
Change for #99 
Changed the chance of wiggling up to 60% from 40%, left cooldown at 2sec.
=> Various Patches 2

code/game/jobs/access.dm, code/game/machinery/bots/farmbot.dm, code/game/machinery/computer/communications.dm, code/stylesheet.dm
Fix for #271 
Added a CSS style for .sergal, light-blue.
Fix for #274 
Added the new CC titles to the already-hardcoded list of titles checked by the HUD.
Change for #117 
Removed the difference between heads and captains when checking for IDs on this console.
Work on #63 
Cleaned up some references to make them make sense in Bay, but still lots of work to do. Left it unchecked in .dme.
=> Various Patches

code/modules/hydroponics/seed_machines.dm
Previous update (Fixing #42) made these machines constructable.  Even
better that they be deconstructable as well!
To this end I added the parts to the contents in the constructors.
I also noticed it was using outdated code to handle opening the panel and deconstructing, so I upgraded to use the new machinery default methods.
=> Make Xenobotany Machines Deconstructable

code/game/jobs/job_controller.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/setup.dm
job_controller.dm was hardcoded to give tajarans and unathi sandals and
nobody else. Now it uses equip_problems flags.
Also cleaned up the station species file in general. It was a bit chaotic.
Fixes #284
=> Species equip_problems flag to help with job_controller et al.

code/modules/clothing/spacesuits/rig/rig.dm, nano/templates/hardsuit.tmpl
Adds a bar displaying pressure, plus the specified release pressure in
parenthesis after the actual kPa pressure value.
Fixes #139
=> Airtank status on hardsuit interface

code/modules/mob/new_player/sprite_accessories.dm
Ckeys need to be lowercase for comparison of custom item ownership.
=> Fixed capitolization on custom char fluff

code/modules/mob/holder.dm, code/modules/mob/living/carbon/carbon.dm
This rewrites the code for grabbing micros with your feet using the grab
intent. Now it uses the get_scooped proc on the mob instead of manually
constructing a holder.
Fixes #292
=> Fix for micro holder in paw-grab

code/game/jobs/job/engineering.dm
The atmos techs were previously just given the assistant backpack for some
reason. This changes it to be the normal engineering backpack.
Fixes #323
=> Changes atmospherics backpack from generic

code/modules/mob/living/carbon/human/species/station/station.dm
Sprites are already in the game, under "icons/mob/human_races/r_skeleton.dmi" so sprites aren't needed for this. Tested and made sure this works.
PROS:
+Cold immunity
+Increased heat resistance
+Immune to toxins
+No need to breathe
+Has no blood.
NEUTRAL:
/Has no special attack.
/Feels pain
/Is immune to cold, but will still take brute damage from the vacuum of space.
CONS:
-Unclonable
-Take 1.5x more burn damage 
-Take 1.5x more brute damage
=> Adds a skeleton race for SilverTalismen

code/modules/client/preferences_savefile.dm
This fix enables inside flavor text to actually save. Fully tested and working. 
No bugs were present during the test. Fixes issue #348 
Reposting this since github decided it'd be a /great/ idea to automatically switch a branch I was working on to this branch, so it totally screwed it up. Fixed now, and it shouldn't happen again.
=> Makes inside flavor text save. V2

code/game/objects/items/weapons/handcuffs.dm, code/modules/mob/living/carbon/human/inventory.dm
Makes it so handcuffs only need a passive grab, as opposed to a aggressive  grab.
Fixes issue #309
=> Handcuffs grab fix

code/modules/mob/language.dm, code/modules/mob/living/carbon/human/species/station/station.dm
Fixes the Sergal from losing it's language due to an error with a character in the language name causing it to automatically change when the file is touched.
Also allows galactic common to be used by races that normally don't start with it by using :c , as opposed to the :0 command which was broken.
Fixes issue #340
=> Sergal Language Hotfix

code/game/objects/items/devices/PDA/PDA.dm
Lowered PDA's weight class to tiny, making it able to fit in the ear slot like it did with the old code. Is probably implantable now too, which also makes sense.
Thread: http://forum.vore-station.net/viewtopic.php?f=20&t=458
=> PDA able to fit in ear slot

code/modules/mob/living/carbon/human/species/station/station.dm
Removed the NO_SCAN flag by popular demand.
http://forum.vore-station.net/viewtopic.php?f=20&t=470
In the future we will remove it, but give slime people another means of IC revivial (e.g. injecting core, xenobio cloner). However, those more preferable options will take time to code so, this is just a hold-over.
=> Made slime race clonable.

code/modules/mob/new_player/sprite_accessories.dm
Makes the Sergal hair styles, added by  #381 able to be used, as it wasn't coded in the original PR.
=> Makes new Sergal hairstyles able to be used.

code/modules/vore/vore.dm
Makes it so you can remove the "They have a lump in their tail message" by spitting out the contents of the tail as normal.
=> Fixes tail vore examine message.

code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/new_player/sprite_accessories.dm, code/setup.dm
Male Slime people can now have beards (presumably slime beards).
Also added a flag for on_mob_life procs exclusive to slime people. (on_mob_life is used for metabolizing, I think). This provides a means to check if someone is a slime person during metabolism of chemicals and such. Could be useful if we want slime persons to have different reactions to chemicals.
=> Slime beards and slime reagent flag

code/datums/wires/vending.dm, code/game/machinery/vending.dm
Fixes issue #389 by making it so it'll show up in admin logs and warn admins when a player:
Uses a screwdriver on a vending machine
Uses wirecutters on a vending machine
Uses a multitool on a vending machine
Electrifies a vending machines
Mends/fixes an electrified vending machine.
=> Warns admins when vending machines are fiddled with.

code/modules/client/preferences_gear.dm, code/modules/clothing/under/miscellaneous.dm
Adds a nudity permit (select able "jumpsuit" that allows players to have all the abilities of a normal jumpsuit, but without the jumpsuit sprite.) and also a mankini, which used to be only obtainable by hacking the clothing vendor.
=> Adds nudity permit (jumpsuit) and mankini.

code/global.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
Adds a xenoarch cyborg that is able to aide in xenoarcheology. 
It is meant to only help, and not be able to do the entirety of xenoarcheology and anomaly research.
**Features**:
Has all needed tools to do xenoarcheology excavation.
Is able to mine out anomalies with no errors, and no required human interaction.
Uses the xenoarcheology specialized drill, instead of the normal xenoarcheology pick set.
Has science radio comms.
**Comments**:
Requires a human to do anomaly research
Requires a human to initially swipe their ID on the suspension generator if the cyborg will be going after artifacts, and not just anomalies.
**Notes**:
Uses the sciency looking mining cyborg sprite and or the mining drone sprite. Depends on which one the user desires/selects.
=> Adds xenoarcheology cyborgs.

code/modules/mob/language.dm
Due to a bug, aka :c already being used for the command channel, you couldn't use galactic common manually. Now you can.
=> Allows races to use galactic common.

code/modules/vore/spiderTaurPowers.dm, code/modules/vore/voretype/tail.dm
Adds a nutrition restriction to web bindings.
Nutrition restriction is 30 units needed. It isn't a lot, but can be changed to be higher if need be.
Without the restriction, you could easily spawn in thousands of web tiles, causing massive lag.
Note: Also fixes a typo in tail vore.
=> Adds restriction to creating web bindings. (Urgent HOTFIX)

code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/setup.dm
https://github.com/SpadesNeil/VOREstation/issues/404
So shoes actually applied a negative slowdown (aka a speedup). I removed this shoe speedup in order to make barefooted people move the same as shoed. However, this would make everyone slower than they currently are, so I had to change default species slowdown to the negative slowdown that shoes used to give.
Tajarans previously had a slowdown of -1, which would be equivalent to -2 now. However, the reason for this was (probably) because many Taj characters would also be barefoot cause paws and stuff. Since that reason is obsolete now that barefoot chars are no longer slowed, I lowered their speedboost by half.
I'd be in favor or removing taj speedboost all together for balance (so everyone has equal speed now). But, people might …
=> Being barefoot no longer slows. Lowered Taj bonus movespeed (reasons inside)

code/stylesheet.dm
It shouldn't have been black. That was a bug.
The color is now: 990033
It's noticably different than the ingame color for blood, in case anyone could get confused from it. But, still keeps the theme nicely I think :3
=> Make daemon language color blood red instead of black.

code/game/objects/structures/crates_lockers/crates.dm, code/modules/mining/abandonedcrates.dm
This will deter players from abusing projectiles to open boxes, as there
is now a chance to destroy the contents and cause a (small) fire, or a
small explosion that will alert security.
Crates will not detonate if unlocked so the CE doesn't have their life
made hell for using an emitter to unlock the supermatter core.
=> Secure crates can be made tamper proof now

code/modules/mob/new_player/sprite_accessories.dm
Exactly what it says on the title.
It lets Tajara and Sergals be able to be able to have no ears (By picking any other hair-style that isn't species specific), allowing them to replace their ears with some from the "ear" style if they desire.
Also lets them choose any of the other pre-existing hair styles currently in game.
=> Lets Tajara and Sergals be able to remove their ears, and choose alt hair styles.

code/game/objects/items/weapons/dogborgstuff.dm, code/modules/reagents/Chemistry-Reagents.dm
Exactly what it says on the title.
Allows borgs to inject "digestive enzymes" into people which does 3 burn damage per tick.
After they die, if the borgs try to inject them with any chemical again, it gives  them a text box, asking if  they'd like to digest the dead person. If  they do so, it'll tell admins and give the borg 30000 charge (As much as a hyper battery)
Also, ignore the last 5 commits at the bottom. There were a few red and  green lines I was trying to fix from showing up in the files list, as I didn't mean to remove them, and I ended up taking a few  tries. Woo.
Also prevents borgs from killing theirselves when trying to inject someone when they're already at the max chemical limit.
Note: Also makes the sleeper take away less power. It was removing power so fast that scenes …
=> Allows borgs to digest people. Notified admins when they do so.

code/game/objects/items/weapons/dogborgstuff.dm, code/modules/mob/living/carbon/human/human.dm
Fixes both #533 and #531 by making the flavor text have a space in beteween prefs and general, and also automatically updates the borg sprites and empties their stomach.
Pref pic: http://puu.sh/oaWHT/ac663ddf58.png
=> Fixes #533 and #531

code/game/objects/items/weapons/dogborgstuff.dm
Makes dogborgs respect digestable pref. Greys out digestive enzymes when prey are indigestible, and prevents you from digesting indigestible bodies.
Added 'Refuel' button to 'finish' digesting, rather than needing to click an unrelated button to get it to proc the dialog. Only lights up with dead prey who have digestion on.
Fixed Scan button and makes the page refresh when injecting as well.
Can't inject with < 800 energy rather than 750. Still costs 750, but "750 < 750 = false". Could still inject chems and one-click kill yourself. So here's a 50 energy safety net. Keep in mind it's 5 energy per tick on these.
No longer does patient.stat == dead or patient.stat != dead. Don't do direct comparisons on bitfields, and instead, use bitwise operators.
Can't inject innaprov into dead patients …
=> Dogbot QOL Tweaks

code/modules/client/preferences.dm, code/modules/mob/living/carbon/human/human.dm, code/setup.dm
Increases the max character limit for preferences.
This includes:
**General
Preferences
Limb-Descriptions**
It increases it from 1024 to 3072, as much as a peice of paper per limb/general/pref.
My main concern for this was that it might lag out the client, or cause the client to lag at all.
I tested this out, and it turns out that it doesn't lag at all. Even with the increase of the word limit in prefs.
This allows people that wish to write more words in their flavor text and preferences, meaning that if someone wishes to write a huge blurb for their character, or list a huge amount of prefs in their prefs list, they can.
Note: I marked it major, as it increases the flavor text limit a large amount, allowing people to put down more prerfs and info about their character.
=> Increases the max character limit for preferences.

VOREStation.dme, code/controllers/configuration.dm, code/game/jobs/job/job.dm, code/game/jobs/job/special.dm, code/game/jobs/job_controller.dm, code/game/jobs/jobs.dm, code/game/jobs/whitelist.dm, code/modules/client/preferences.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/new_player/new_player.dm, config/example/config.txt, config/example/jobwhitelist.txt
This allows any job to be set to require whitelisting by adding the var
"job_whitelisted = 1" to the settings for the job. It also adds a "Unique"
department, and an example job, "CentCom Observer", in a new special.dm
file for the special whitelist/admin jobs. There's no config file for
WHICH jobs are whitelisted yet.
Admins always ignore the whitelist.
This makes the job priorities screen ugly, sorry. It will look nicer when
that third column has more jobs in it, or someone who knows more
HTML-as-tortured-by-Byond can take a crack at it.
**_THINGS YOU SHOULD KNOW:_**
You must create jobwhitelist.txt in the config folder. After updating,
there will be a copy in config/example.
There is a new config file option, USEJOBWHITELIST, that you need to add
to enable job whitelists. Until then, …
=> Job Whitelist

code/defines/obj/weapon.dm, code/game/objects/items/weapons/storage/storage.dm
Makes the RPED able to hold beakers, and makes storing an item message show the icon so you can't name a paper "emag" or whatever.
=> RPED beakers and storage icons

code/game/machinery/autolathe.dm, code/game/machinery/autolathe_datums.dm
Two changes made:
1. Add a recipe to autolathe to produce cable coils.   This is added as an `is_stack = 1` recipe (which tells the autolathe to correctly calculate materials cost for producing stacks)
2. While fixing I noticed that autolathe doesn't limit to the maximum stack size for a stack type.  This normally would not be noticed since metal/glass are expensive enough you'd not have that much loaded in the lathe anyway.  Wires are cheap enough that it is apparent.
=> Cable coils 482

code/modules/power/sensors/sensor_monitoring.dm
- power_monitor is initialized after a 50 decasecond delay.
- check_warnings() which is called by process() which is called by a
controller references power_monitor.
- Therefore a race condition allows referencing before it is initialized.
- Solution: Just check if its null, so controller ticks prior to init
won't boom.
=> Fixes #638 By handling race condition.

code/modules/admin/verbs/randomverbs.dm
Adds it onto the name of both the mesage in communications computer and
the name of the paper report.
Example: Central Command Update (12:05)
=> Resolves #606 - Adds timestamp to Command Report name.

code/game/machinery/bots/bots.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/living/simple_animal/hostile/vore/vore.dm
/obj/machinery/bot did not implement any behavior on attack_generic, which
is what hostile mobs call on them. The only reason it compiled is because
/obj itself has attack_generic stub with a return in it.
Added an attack_generic proc on bots, and modified hostile code to only
attack 'on' bots. (Why woud a carp care about a thing that looks like a
bucket when it's not moving?)
Also fixed several runtimes with trying to check the digestability of a
bot.
Fixes #657
=> Fix for #657

code/modules/mob/living/simple_animal/hostile/vore/vore.dm
Stops updating mob icons if the mob is dead.
Fixes #661
=> Fix for #661

code/modules/organs/blood.dm
Bails out of the blood splatter proc early in blood.dm if the place we're
in is not a turf (also causes lockers to not leak blood which is too bad,
owell.)
Fixes #650
=> Fix for #650

VOREStation.dme, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/vore/resize.dm
Removed the math that was causing the sprites to be misaligned on taurs
that were not scale 1.0 when recalculating tail visibility.
Also moved Resize to Vore because that tab was boring and now gone.
Fixes #231
=> Fix for #231

code/game/objects/items/robot/robot_upgrades.dm
#629 
Exactly what it says on the tin. 
I was also going to fix the "Resetting the borg to normal charge" part attached to the issue, but I didn't see exactly where it could be fixed without causing issues. (Ex: Borg infinitely charging with no stop), and this is the biggest problem in that issue request. Borgs walking into a charger with above max charge really isn't a huge issue.
=> Fixes cyborg sprite when reset module is used #629

code/datums/helper_datums/teleport.dm, code/game/objects/items/devices/radio/beacon.dm
Fixes #676
Also improves telenoms by letting you stick the beacon in your tailhole
(or, you know, wherever really) then prey get teleported there. If you're
just standing on a beacon, first belly is picked. If you have more than
one beacon, the 'last' one in you is used. Don't eat a bunch of beacons
though, you ass.
=> Fix for #676 plus improvements

code/game/machinery/cloning.dm, code/modules/client/preferences.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/vore/vore.dm
Fixes #674, and also fixes the stupid 'collapsing' messages you can see
while someone is inside a belly. Changes them to visible_message which
should prevent people from 'seeing' it when they can't 'see' the person.
=> Fix for #674 + message tweak

code/game/dna/dna_modifier.dm, code/game/machinery/computer/cloning.dm, code/game/machinery/cryopod.dm
Makes cryo search people for health implants, and deletes the associated
record from the scanning database whenever the person is deleted for cryo
purposes. Also made the proc for finding preserved items less expensive.
Surely there was an issue about this at some point? Maybe not anymore?
=> Fix for scan->cryo->rejoin->scan

code/modules/mob/living/carbon/human/examine.dm
Bottom of examine text. Technically not ACTUALLY scan status, just scans
for those little-known health implants. So technically possible to fool
with a bit of surgery or adminbuse or an event or something that gives
someone an implant. Even holding one works.
=> MedHud shows scan status

code/modules/mob/living/carbon/human/examine.dm, code/modules/vore/belly/belly.dm, code/modules/vore/vore_panel.dm
This wasn't intentionally removed, but sorta half-broken. So now you can edit your belly's examine text messages, and by that I mean the messages it gives to people who examine you when you have someone/something in a belly.
"Their taurguts are swinging a bit low."
etc.
=> The return of bellytext in examines
